name: 🚀 Deploy Laravel via SSH + Git Pull

on:
  push:
    branches:
      - main  # Укажи свою основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Установка SSH-соединения
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 📦 Подключение по SSH и деплой
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}
            git reset --hard
            git pull origin main
            composer install --no-dev --optimize-autoloader
            npm install && npm run build
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
            php artisan queue:restart
            chmod -R 775 storage bootstrap/cache
          EOF
